package com.alox1d.vkvoicenotes.internal

const val DATABASE_NAME = "voicenotes.db"
const val REQUEST_PERMISSION_READ_EXTERNAL_STORAGE_CODE = 7031
const val REQUEST_PERMISSION_RECORD = REQUEST_PERMISSION_READ_EXTERNAL_STORAGE_CODE + 1
